### ISSUE TITLE
refresh token not work

### ISSUE THREAD

**Issue by timeshift92** [RodolfoSilva/hasura-auth#2]
and in user_session table not find field refresh_token

**Comment by RodolfoSilva** [comment]
Hm, I'll fix that. Thanks @timeshift92

**Comment by RodolfoSilva** [comment]
Column added in https://github.com/RodolfoSilva/hasura-auth/commit/180664c3a5c3bf3206db67c2e15bde21816aedb4

**Comment by timeshift92** [comment]
thanks
