### ISSUE TITLE
Resources on Client side examples

### ISSUE THREAD

**Issue by templatedop** [RodolfoSilva/hasura-auth#25]
Hi,

Can you please share some client side examples.

Firstly I would like to check the details in Hasura console itself. I don't how to do .

Bit of confusion on JWT token. Could understand that JWT private key for server side encryption.

But what about client side. Is it private key or public key.

Please guide.

**Comment by RodolfoSilva** [comment]
I am no longer working on this project. I recommend you to use [hasura-backend-plus](https://github.com/nhost/hasura-backend-plus).

HB+ is more stable and has a bigger team to help you.

I'll close this issue, fell free to reply.
