### ISSUE TITLE
A way to disable user registration

### ISSUE THREAD

**Issue by mihazs** [RodolfoSilva/hasura-auth#7]
Hello.

I need a way to disable the user signup. The registration of new users will be done by the admin of the system, and the new users can't signup by themselves 
It's possible to have a env var to disable the signup mutation?

**Comment by RodolfoSilva** [comment]
I think we can implement this. :D I'll try latter. I've now the same use case. Thanks.

**Comment by RodolfoSilva** [comment]
Thanks @mihazs, PR: #9
